### ISSUE TITLE
Editing existing Combos doesn't work

### ISSUE THREAD

**Issue by sleeping-dev** [Breadkenty/Smash_Combos#28]
When editing an existing combo and trying to submit it, a message shows up that says 'The Email field is required'.
Not quite sure where this comes from, and we haven't really touched the frontend stuff lately so I don't know when this was introduced, but it's been preventing me from testing the Mediator-Methods for PutCombo, so i figured I'd make an issue.

To reproduce this:
- Make a combo and submit it
- Press the edit button when viewing the combo
- Navigate down the page and press 'submit'
- The above mentioned message will show up, preventing the submit

This happens on the staging site too, so it's not something I introduced during my current local changes.

**Comment by skittlz444** [comment]
@sleeping-dev This is an issue affecting more than just this, you are not able to create combos or comments either. This is probably due to the either the front end requiring information that's no longer sent (i.e. more in depth user data) or the backend expecting it. This happened due to moving the get combo(s) and comment(s) logic to the core and cutting down the response. This isn't a fault of the core response, but rather how the front end is coupled to the relationship between combo/comment and user. It doesn't make sense to require the user's email in order to create a combo, however we should need their user id. Moving the post and put logic for everything into the core, not relying on requests and responses structured exactly like domain entities in the UI should fix this issue. Will look into it on your branch and see what I can do.

**Comment by skittlz444** [comment]
Ok so from what I can gather, this is most likely an issue in the front end react UI. Didn't have time to track down where exactly unfortunately.

**Comment by sleeping-dev** [comment]
It says you're a collaborator with access to the repo, it should work? Unless I need to change some settings to let you clone it?

I am able to create combos and comments on [the staging site](http://smash-combos-dev.herokuapp.com) though. Just editing is when the bug pops up. I agree, probably a front end issue.

**Comment by sleeping-dev** [comment]
Fix has been found, I'll include it in #27

**Comment by sleeping-dev** [comment]
I'm gonna go ahead and close this, this has been solved.
